### ISSUE TITLE
Is it still an open issue if ROC should be encrypted or not ?

### ISSUE THREAD

**Issue by fluffy** [ietf/perc-wg#14]

**Comment by paulej** [comment]
If Alice sends a stream of media packets to the MDD, participants joining at the same time would assume the initial ROC value is 0 and could decrypt the end-to-end encryption.

As the conference continues, Alice's ROC will increment.  So, let's say her ROC value is now 100.

If a new participant Bob then joins the conference, Bob would not know Alice's ROC value.  Her ROC value would need to be communicated to Bob in order for Bob to properly decrypt the packet end-to-end.  To address this, https://tools.ietf.org/html/draft-jones-perc-private-media-framework-01 proposed pulling the ROC out and putting it in the clear (XORing the value with the Alternative IV in order to ensure integrity).  However, with "double", packets is integrity checked hop-by-hop, so that XOR step might not be necessary.  So, putting it in the clear might be helpful.

Alternatively, the ROC could be added to the OHB defined in "Double".

Whatever the case, Bob will need to know the ROC used for E2E encryption.

**Comment by fluffy** [comment]
So just thinking out aloud ... when Bob joins, his does DTLS-SRTP getting the EKT parameter set in use. Within 100ms he gets a Full EKT Field which he decrypts and gets the ROC. I'm not seeing how a non encrypted ROC helps. If that ROC was not encrypted, it seems like Bob still needs the SRTP_Master_Key and has to wait for a Full EKT Field to get ti.

**Comment by paulej** [comment]
Doh!  OK, this is the second time I've made that mistake.  Sorry.  Yes, he can decrypt the EKT field and get the ROC.  Let's just pretend I didn't write that long and broken explanation.

**Comment by suhasHere** [comment]
Agree to stay with encrypted version as it puts all the crypto context in one place .. Close this issue?
