### ISSUE TITLE
Truncate salt when it is too long

### ISSUE THREAD

**Issue by fluffy** [ietf/perc-wg#26]
Add stuff to say if the srtp_master_salt in the EKTkey is longer than the salt needed by the SRTP crypto in use, it can be truncated.

**Comment by paulej** [comment]
Good, since that's effectively what folks did when introducing encrypted header extensions.  For AES-GCM, the salt length is shorter than AES-CM.  So for AES-GCM, the key (128 bit) and salt (96 bit) will not work to encrypt header extensions.  What folks did was just pass a 128 bit salt and a 112 bit key.  For AES-GCM, 96 bits of the salt were used.  Within the same session, the additional salt bits are used for the header extension encryption using AES-CM (via the KDF used to derive the keys for header extension encryption per RFC 6904).
