### ISSUE TITLE
Specify recipient behavior when SRTP packet is received with MKI ...

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#45]
Section 2 (para 2)
   EKT MUST NOT be used in conjunction with SRTP's MKI (Master Key
   Identifier) or with SRTP's <From, To> [RFC3711], as those SRTP
   features duplicate some of the functions of EKT.

>>> Do you expect implementations to check for this MUST NOT?
>>> If so, what should the recipient do if the sender does use EKT
>>> in conjunction with SRTP's MKI or with SRTP's <From, To> ?

Same issue has be raised by Spt 
>>>What happens if an implementation does use SRTP's MKI or with SRTP's <From, To>?  Is an error thrown?

**Comment by paulej** [comment]
I do expect they'd check, because they have to know how to parse the packet and where to insert the EKT field.  With EKT, the key to use is conveyed via the RTP packet.  Only after the EKT field is parsed would it make sense to look to find an MKI value.

In any case, if MKI is used it's just redundant.

One thing I didn't see in reviewing the current specs is where the EKT field should be inserted.  It should be inserted on the inner encryption step of double.  The outer encryption is consumed by intermediaries and they don't understand EKT.

We probably need to put that back into the framework document.  The packet format was removed during one revision.

**Comment by fluffy** [comment]
opened new bug for where EKT goes
