### ISSUE TITLE
Add Packet format showing double +  ekt in framework space

### ISSUE THREAD

**Issue by suhasHere** [ietf/perc-wg#66]

**Comment by fluffy** [comment]
Just looking at framework and it does not seem like there is any good place to include a SRTP+EKT packet figure. Perhaps one of the other specs is better

**Comment by paulej** [comment]
I think the framework is best.  Could be an appendix or annex.  (Not sure if there is a distinction in IETF RFCs.)  I have no strong preference, but it seems like every spec is the wrong place.  "Double" can stand on it's own, so not the right place.  "EKT Diet" doesn't strictly have to be used with PERC or Double, so not the right place.  Tunnel has no relationship at all.

So, I think the framework or some new draft, but I don't know what else such a draft would have.  It needs to be more than informational, though.

**Comment by fluffy** [comment]
I think I am leaning towards we start and perc-examples draft as david mentioned but agree with your logic.

**Comment by paulej** [comment]
You agree this would be a normative spec?  If so, perhaps "examples" might sound informative.  We need to show what a PERC packet looks on the wire, something similar to what we have in RFC 3711 and what I put into the original framework proposal.

There are also some procedural bits that are normative that I think might be good candidates for such a draft.  Right now, I don't recall what the other things were.  Maybe we need to make a list.  This issue can be used for those things.

One is related to issue #69.  We need a place that explains to the endpoint developers they consideration needs to be given to the dtls-id.  Perhaps we put the endpoint-specific procedures into this text.  Makes more sense there than in tunnel, as an endpoint developer otherwise does not need to read the tunnel draft.

**Comment by fluffy** [comment]
yah ... you once we have a list, might become clearer. it's possible the dtls-id needs to go in the signaling draft

**Comment by suhasHere** [comment]
@paulej , @fluffy  where are we on this ?

**Comment by paulej** [comment]
I wrote an initial draft and sent it to David.

**Comment by fluffy** [comment]
This ended up in the end of double draft. If someone wants to move it to framework, lets just handle that as separate issue.

**Comment by paulej** [comment]
It was in the last framework draft.
